name: Lint and Format

on:
  push:
    branches:
      - '*'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # TODO: Confirm node version after create next app

      - name: Install dependencies
        run: |
          npm ci

      - name: Run ESLint
        # TODO: Confirm path after create next app
        run: |
          npx eslint . --max-warnings=0

      - name: Run Prettier check
        # TODO: Confirm path after create next app
        run: |
          npx prettier . --check